# Generated by Django 2.1.3 on 2019-02-03 01:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20190203_0045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlikes',
            unique_together={('user', 'comment')},
        ),
    ]
